### ISSUE TITLE
Cannot edit an address

### ISSUE THREAD

**Issue by sgjenks01** [FactomProject/enterprise-wallet#11]
I am running Enterprise Wallet Version v0.1.2.0  The wallet has loaded and reports 100% complete. I created an address and sent some FCT to the address. The wallet shows that balance. Next, I clicked on Address Book and then clicked on the blue pencil where I wanted to record the seed. The center panel in the wallet went blank. I closed the wallet and restarted. When I repeated the above steps, I got the same result. 

Now what?

**Comment by Emyrk** [comment]
The latest version of EnterpriseWallet addresses this issue
