### ISSUE TITLE
Run wallet in Linux server

### ISSUE THREAD

**Issue by erotundo** [FactomProject/enterprise-wallet#6]
Hi!.

After install factom into my server and run factomd i will try to run enterprise-wallet using command "enterprise-wallet" but the console tell me localhost:8091 runs but i cannot enter into this port and directions but to factomd i can enter. The console don't show me a error to guide me into solution

Regards

ER

**Comment by Emyrk** [comment]
Is this still an issue? If so, can you paste the output following execution?
Also are you running factom-walletd as well?

**Comment by Emyrk** [comment]
Closing as this ticket it quite dated and there is no response
